version: '2'
services:

  # API #
  ## Application ##
  api-app:
    build:
      context: ./api/
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      # Assumes "api" project is 1 level up
      - ./../api/:/var/www
    env_file:
      - ./api/api.env
  ## Nginx ##
  api-nginx:
    build:
      context: ./api/
      dockerfile: nginx.dockerfile
    working_dir: /var/www
    volumes_from:
      - api-app
    ports:
      - 8888:80

  # Consumer web #
  ## Application ##
  consumer-web-app:
    build:
      context: ./consumer-web/
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      # Assumes "consumer-web" project is 1 level up
      - ./../consumer-web/:/var/www
    env_file:
      - ./consumer-web/consumer-web.env
  ## Nginx ##
  consumer-web-nginx:
    build:
      context: ./consumer-web/
      dockerfile: nginx.dockerfile
    working_dir: /var/www
    volumes_from:
      - consumer-web-app
    ports:
      - 8889:80

  ## Backing services ##
  redis:
    image: redis
    ports:
      - "6379"
  database:
    build:
      context: ./
      dockerfile: ./database.dockerfile
    ports:
      - '54321:5432'

