version: '2'
services:

  # API #
  ## Application ##
  api-app:
    build:
      context: ./
      dockerfile: ./api.app.dockerfile
    working_dir: /var/www
    volumes:
      # Assumes "api" project is 1 level up
      - ./../api/:/var/www
    environment:
      - "DB_PASSWORD=secret"
      - "DB_PORT=3306"
      - "DB_HOST=database"
  ## Nginx ##
  api-nginx:
    build:
      context: ./
      dockerfile: ./api.nginx.dockerfile
    working_dir: /var/www
    volumes_from:
      - api-app
    ports:
      - 8888:80

  # Consumer web #
  ## Application ##
  consumer-web-app:
    build:
      context: ./
      dockerfile: ./consumer-web.app.dockerfile
    working_dir: /var/www
    volumes:
      # Assumes "consumer-web" project is 1 level up
      - ./../consumer-web/:/var/www
    environment:
      - "DB_PASSWORD=secret"
  ## Nginx ##
  consumer-web-nginx:
    build:
      context: ./
      dockerfile: ./consumer-web.nginx.dockerfile
    working_dir: /var/www
    volumes_from:
      - consumer-web-app
    ports:
      - 8889:80

  ## Backing services ##
  redis:
    image: redis
    ports:
      - "6379"
  database:
    build:
      context: ./
      dockerfile: ./database.dockerfile
    ports:
      - '54321:5432'

