version: '2'
services:

  # API #
  ## Application ##

  # @todo Need to increase memory limit for unit testing
  api-app:
    container_name: foodkit.api
    mem_limit: 1g
    environment:
      - APT_MIRROR="${APT_MIRROR}"

    build:
      context: ./api/
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      # Assumes "api" project is 1 level up
      - ./../api/:/var/www
    env_file:
      - ./api/api.env
    links:
      - database
      - redis
      - beanstalk

  ## Nginx ##
  api:
    container_name: foodkit.api.nginx
    #? mem_limit: 20m

    build:
      context: ./api/
      dockerfile: nginx.dockerfile
    working_dir: /var/www
    volumes_from:
      - api-app
    ports:
      - 8888:80

  # Consumer web #
  ## Application ##
  consumer-web-app:
    container_name: foodkit.cw
    mem_limit: 500m


    build:
      context: ./consumer-web/
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      # Assumes "consumer-web" project is 1 level up
      - ./../consumer-web/:/var/www
    env_file:
      - ./consumer-web/consumer-web.env
    links:
      - redis

  ## Nginx ##
  consumer-web:
    container_name: foodkit.cw.nginx

    build:
      context: ./consumer-web/
      dockerfile: nginx.dockerfile
    working_dir: /var/www
    volumes_from:
      - consumer-web-app
    ports:
      - '8889:80'

  ## Backing services ##
  redis:
    container_name: foodkit.redis
    image: redis
    ports:
      - "6379"

  ## Postgresql
  database:
    container_name: foodkit.db
    build:
      context: ./database/
      dockerfile: database.dockerfile
    ports:
      - '54321:5432'

  redis:
    container_name: foodkit.redis
    image: redis
    ports:
      - "6379"

  beanstalk:
    container_name: foodkit.beanstalk
    image: schickling/beanstalkd
    ports:
      - "11300"
